[package]
name = "dlpack"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.16", optional = true }
pyo3 = { version = "0.26", optional = true }

[features]
ndarray = ["dep:ndarray"]
pyo3 = ["dep:pyo3"]
